/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  altmf
 * Created: 08.02.2017
 */
CREATE TABLE if not exists makpsb.report_info(
                                                 id              BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                                 is_deleted      INT DEFAULT 0,
                                                 visible_name    text,
                                                 path            varchar(1023),
                                                 class_name      varchar(1023),
                                                 PRIMARY KEY	 (id)
);

