/* 
 * TO CHANGE THIS LICENSE HEADER, CHOOSE LICENSE HEADERS IN PROJECT PROPERTIES.
 * TO CHANGE THIS TEMPLATE FILE, CHOOSE TOOLS | TEMPLATES
 * AND OPEN THE TEMPLATE IN THE EDITOR.
 */
/**
 * AUTHOR:  ALTMF
 * CREATED: 22.04.2017
 */

SELECT NAME, G.* FROM(
    SELECT ID_SIGNATURE_TYPE, COUNT(ID) AS SIGNATURE
    FROM MP_INCREM.CLS_SIGNATURE  AS S   
    GROUP BY ID_SIGNATURE_TYPE
) AS G 
INNER JOIN MP_INCREM.CLS_SIGNATURE_TYPE AS T ON G.ID_SIGNATURE_TYPE = T.ID
;
SELECT NAME, G.* FROM(
    SELECT ID_SIGNATURE_TYPE, SUM(C) as count_detected
    FROM MP_INCREM.CLS_SIGNATURE  AS S   
    INNER JOIN (
        SELECT ID_SIGNATURE, COUNT(SNILS) AS C FROM 
        (SELECT DISTINCT ID_SIGNATURE, SNILS FROM MP_INCREM.REG_DETECTED_SIGNATURE) AS D
        GROUP BY  ID_SIGNATURE
    ) AS V
    ON S.ID = V.ID_SIGNATURE
    GROUP BY ID_SIGNATURE_TYPE
) AS G 
INNER JOIN MP_INCREM.CLS_SIGNATURE_TYPE AS T ON G.ID_SIGNATURE_TYPE = T.ID
;
SELECT T.NAME, TT."NAME",  G.* FROM(
    SELECT ID_SIGNATURE_TYPE, ID_SIGNATURE, SUM(C) as count_detected
    FROM MP_INCREM.CLS_SIGNATURE  AS S   
    INNER JOIN (
        SELECT ID_SIGNATURE, COUNT(SNILS) AS C FROM 
        (SELECT DISTINCT ID_SIGNATURE, SNILS FROM MP_INCREM.REG_DETECTED_SIGNATURE) AS D
        GROUP BY  ID_SIGNATURE
    ) AS V
    ON S.ID = V.ID_SIGNATURE
    GROUP BY ID_SIGNATURE_TYPE, ID_SIGNATURE
) AS G 
INNER JOIN MP_INCREM.CLS_SIGNATURE_TYPE AS T ON G.ID_SIGNATURE_TYPE = T.ID
INNER JOIN MP_INCREM.CLS_SIGNATURE AS TT ON G.ID_SIGNATURE = TT.ID
;
-- MAX DETECTED
SELECT NAME, G.* FROM(
    SELECT ID_SIGNATURE_TYPE, SUM(C) as count_detected
    FROM MP_INCREM.CLS_SIGNATURE  AS S   
    INNER JOIN (
        SELECT ID_SIGNATURE, COUNT(SNILS) AS C FROM 
        (SELECT DISTINCT ID_SIGNATURE, SNILS FROM MP_INCREM.MAX_DETECTED_SIGNATURE) AS D
        GROUP BY  ID_SIGNATURE
    ) AS V
    ON S.ID = V.ID_SIGNATURE
    GROUP BY ID_SIGNATURE_TYPE
) AS G 
INNER JOIN MP_INCREM.CLS_SIGNATURE_TYPE AS T ON G.ID_SIGNATURE_TYPE = T.ID
;
SELECT T.NAME, TT."NAME",  G.* FROM(
    SELECT ID_SIGNATURE_TYPE, ID_SIGNATURE, SUM(C) as count_detected
    FROM MP_INCREM.CLS_SIGNATURE  AS S   
    INNER JOIN (
        SELECT ID_SIGNATURE, COUNT(SNILS) AS C FROM 
        (SELECT DISTINCT ID_SIGNATURE, SNILS FROM MP_INCREM.MAX_DETECTED_SIGNATURE) AS D
        GROUP BY  ID_SIGNATURE
    ) AS V
    ON S.ID = V.ID_SIGNATURE
    GROUP BY ID_SIGNATURE_TYPE, ID_SIGNATURE
) AS G 
INNER JOIN MP_INCREM.CLS_SIGNATURE_TYPE AS T ON G.ID_SIGNATURE_TYPE = T.ID
INNER JOIN MP_INCREM.CLS_SIGNATURE AS TT ON G.ID_SIGNATURE = TT.ID
;